[debug] [2018-11-10T21:28:03.976Z] ----------------------------------------------------------------------
[debug] [2018-11-10T21:28:03.977Z] Command:       /usr/bin/node /usr/bin/firebase serve
[debug] [2018-11-10T21:28:03.977Z] CLI Version:   6.0.1
[debug] [2018-11-10T21:28:03.978Z] Platform:      linux
[debug] [2018-11-10T21:28:03.978Z] Node Version:  v10.12.0
[debug] [2018-11-10T21:28:03.978Z] Time:          Sat Nov 10 2018 22:28:03 GMT+0100 (Central European Standard Time)
[debug] [2018-11-10T21:28:03.978Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-11-10T21:28:03.983Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-11-10T21:28:03.984Z] > authorizing via signed-in user
[debug] [2018-11-10T21:28:03.984Z] [iam] checking project appointments-pwa for permissions ["firebase.projects.get"]
[debug] [2018-11-10T21:28:03.985Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/appointments-pwa:testIamPermissions  

[debug] [2018-11-10T21:28:04.963Z] <<< HTTP RESPONSE 200
[debug] [2018-11-10T21:28:04.966Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/appointments-pwa  
 
[debug] [2018-11-10T21:28:05.977Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/home/kaindl/Documents/appointments-pwa'...
[info] 
[debug] [2018-11-10T21:28:06.333Z] Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.mkdirSync (fs.js:750:3)
    at Object.assertLogsPath (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/lib/node_modules/firebase-tools/lib/functionsEmulator.js:102:23)
    at Object.start (/usr/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /usr/lib/node_modules/firebase-tools/lib/serve/index.js:18:23
    at arrayMap (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/lib/node_modules/firebase-tools/lib/serve/index.js:16:26)
    at Command._action (/usr/lib/node_modules/firebase-tools/lib/commands/serve.js:58:12)
[error] 
[error] Error: An unexpected error has occurred.
